import { 莫红袖 } from "./莫红袖";
import { 禺期 } from "./禺期";
import { 田偌 } from "./田偌";
import { 焰响 } from "./焰响";
import { 林 } from "./林";
import { 温留 } from "./温留";
import { 云无月 } from "./云无月";
import { 乐无异 } from "./乐无异";
import { 修 } from "./修";
import { 唐路遥 } from "./唐路遥";
import { 豹富 } from "./豹富";
import { 尤尼 } from "./尤尼";
import { 昊苍 } from "./昊苍";
import { 织雪 } from "./织雪.ts";
import { 百里屠苏 } from "./百里屠苏";
import { 米达斯 } from "./米达斯";
import { 十手卫 } from "./十手卫";
import { 明月尘 } from "./明月尘";
import { 景 } from "./景";
import { 耶芙娜 } from "./耶芙娜";
import { 无咎 } from "./无咎";
import { 比戈尼娅 } from "./比戈尼娅";
import { 白鸟梓 } from "./白鸟梓";
import { 霍冉 } from "./霍冉";
import { 马尔斯 } from "./马尔斯";
import { SweeperEX } from "./Sweeper-EX";
import { 玄戈 } from "./玄戈";
import { 茜茜 } from "./茜茜";
import { 鸢 } from "./鸢";
import { 司旸 } from "./司旸";
import { 崔远之 } from "./崔远之";
import { 红玉 } from "./红玉";
import { 凤无梦 } from "./凤无梦";
import { 吉娜 } from "./吉娜";
import { 司危 } from "./司危";
import { 雪长夏 } from "./雪长夏";
import { 狄砚 } from "./狄砚";
import { 艾摩诃 } from "./艾摩诃";
import { 卯绒绒 } from "./卯绒绒";
import { 旒珠 } from "./旒珠";
import { 龙和 } from "./龙和";
import { 余音 } from "./余音";
import { 瞳 } from "./瞳";
import { 缇诗 } from "./缇诗";
import { 风晴雪 } from "./风晴雪";
import { 罗咤 } from "./罗咤";
import { 卡洛琳 } from "./卡洛琳";
import { 莉缇亚 } from "./莉缇亚";
import { 尚非乐 } from "./尚非乐";
import { 刘兄 } from "./刘兄";
import { 龙晴 } from "./龙晴";
import { 谛卡 } from "./谛卡";
import { 珑 } from "./珑";
import { 言御 } from "./言御";
import { 紫都 } from "./紫都";
import { 芙蕖 } from "./芙蕖";
import { 苏筱 } from "./苏筱";
import { 阳铃 } from "./阳铃";
import { 长谣 } from "./长谣";
import { 元桃桃 } from "./元桃桃";
import { 红珠小姐 } from './红珠小姐';
import { 提提亚 } from "./提提亚";
import { 拉波 } from "./拉波";
import { 伊琅相思 } from "./伊琅相思";
import { 北洛 } from "./北洛";
import { 岑缨 } from "./岑缨";
import { 逸虚 } from "./逸虚";
import { 言雀 } from "./言雀";
import { 晴雪 } from "./晴雪";
import { 瓦卡莎 } from "./瓦卡莎";
import { 襄铃 } from "./襄铃";
import { 阿棘 } from "./阿棘";
import { 赫九逸 } from "./赫九逸";
import { 岚岚 } from "./岚岚";
import { 老板 } from "./老板";

export default class AllCharHelper {
    static 莫红袖 = 莫红袖;
    static 禺期 = 禺期;
    static 田偌 = 田偌;
    static 焰响 = 焰响;
    static 林 = 林;
    static 温留 = 温留;
    static 云无月 = 云无月;
    static 乐无异 = 乐无异;
    static 修 = 修;
    static 唐路遥 = 唐路遥;
    static 豹富 = 豹富;
    static 尤尼 = 尤尼;
    static 昊苍 = 昊苍;
    static 织雪 = 织雪;
    static 百里屠苏 = 百里屠苏;
    static 米达斯 = 米达斯;
    static 十手卫 = 十手卫;
    static 明月尘 = 明月尘;
    static 景 = 景;
    static 耶芙娜 = 耶芙娜;
    static 无咎 = 无咎;
    static 比戈尼娅 = 比戈尼娅;
    static 白鸟梓 = 白鸟梓;
    static 霍冉 = 霍冉;
    static 马尔斯 = 马尔斯;
    static SweeperEX = SweeperEX;
    static 玄戈 = 玄戈;
    static 茜茜 = 茜茜;
    static 鸢 = 鸢;
    static 司旸 = 司旸;
    static 崔远之 = 崔远之;
    static 红玉 = 红玉;
    static 凤无梦 = 凤无梦;
    static 吉娜 = 吉娜;
    static 司危 = 司危;
    static 雪长夏 = 雪长夏;
    static 狄砚 = 狄砚;
    static 艾摩诃 = 艾摩诃;
    static 卯绒绒 = 卯绒绒;
    static 旒珠 = 旒珠;
    static 龙和 = 龙和;
    static 余音 = 余音;
    static 瞳 = 瞳;
    static 缇诗 = 缇诗;
    static 风晴雪 = 风晴雪;
    static 罗咤 = 罗咤;
    static 卡洛琳 = 卡洛琳;
    static 莉缇亚 = 莉缇亚;
    static 尚非乐 = 尚非乐;
    static 刘兄 = 刘兄;
    static 龙晴 = 龙晴;
    static 谛卡 = 谛卡;
    static 珑 = 珑;
    static 言御 = 言御;
    static 紫都 = 紫都;
    static 芙蕖 = 芙蕖;
    static 苏筱 = 苏筱;
    static 阳铃 = 阳铃;
    static 长谣 = 长谣;
    static 元桃桃 = 元桃桃;
    static 红珠小姐 = 红珠小姐;
    static 提提亚 = 提提亚;
    static 拉波 = 拉波;
    static 伊琅相思 = 伊琅相思;
    static 北洛 = 北洛;
    static 岑缨 = 岑缨;
    static 逸虚 = 逸虚;
    static 言雀 = 言雀;
    static 晴雪 = 晴雪;
    static 瓦卡莎 = 瓦卡莎;
    static 襄铃 = 襄铃;
    static 阿棘 = 阿棘;
    static 赫九逸 = 赫九逸;
    static 岚岚 = 岚岚;
    static 老板 = 老板;
}